### ISSUE TITLE
Is this working now?

### ISSUE THREAD

**Issue by tyeeman** [ratherlongname/zippy-download#1]
I would like to try it if it's working?

**Comment by shivambl** [comment]
Yeah it works.
```
$ python3 zippy-download.py -h
```
Run this command to get yourself started. I'll add detailed instructions on how to run this in the README by a few hours.

**Comment by shivambl** [comment]
I have updated the README with instructions to use this utility. Open another issue if you face any problems or have any suggestions.

**Comment by tyeeman** [comment]
Just tried it, very nice! A lot of these type of scripts will break every time Zippy changes their algorithm. How about yours?

**Comment by shivambl** [comment]
Yeah, mine will break too. 

To remedy this there are two approaches that immediately come to mind-
1. Some complex programme to infer the algorithm from the zippy webpage. This is either too complex a solution for this problem, or will involve eval-ing javascript code from the webpage directly, which is very dangerous to do.
2. Make the exact zippy algorithm an extremely modular part of the script, so that it can be individually updated very easily. If the algo is ever updated, anyone would be able to submit a pull request very easily.

I'll work on the second solution and I think I'll be able to complete it by tomorrow.

**Comment by tyeeman** [comment]
[Here's](https://github.com/victor-oliveira1/ZippyDown/issues/4) a discussion a few of us had on another repo for doing this. Then read the [Readme](https://github.com/victor-oliveira1/ZippyDown). It hasn't been updated for a while so it must be working. I will try it.

**Comment by tyeeman** [comment]
For no. 2 above, would a coder, like you, only be able to update it, or could a techy like me (although, not a coder) do it also?
